apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  type: LoadBalancer
  selector:
    app: yolo-backend
  ports:
    - protocol: TCP
      port: 5000       # External port
      targetPort: 5000 # Container port
