apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
        - name: yolo-frontend
          image: waitheramacharia/yolo-frontend:v1.0.2      # Use the local image
          imagePullPolicy: Always           # Donâ€™t pull from Docker Hub
          ports:
            - containerPort: 80           # Frontend container port
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://yolo-backend:5000"
